# .github/workflows/build.yml
name: Simple Docker Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set repository name lowercase
        id: repo_lower
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr 'A-Z' 'a-z')" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          echo "building image..."
          docker build -t ghcr.io/${{ steps.repo_lower.outputs.REPO_NAME }}:latest -f ./bot_manager/Dockerfile ./bot_manager

      - name: Push Docker image
        run: |
          echo "Push image..."
          docker push ghcr.io/${{ steps.repo_lower.outputs.REPO_NAME }}:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.VPS_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ steps.repo_lower.outputs.REPO_NAME }}:latest
            cd /home/mika/django
            docker compose down && docker compose up -d
            docker logout ghcr.io
      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io
